### ISSUE TITLE
DataTables format: Image links a being replaced in the wrong column

### ISSUE THREAD

**Issue by octfx** [SemanticMediaWiki/SemanticResultFormats#188]
### Setup

- MW version: 1.28.0
- DB (MySQL etc.): MariaDB 10
- PHP version: 7
- SMW version: 2.4.3
- SRF version: master (17.10.2016)

### Issue
The column next to the image links is replaced by DataTables and not the image links itself.  
Example: https://star-citizen.wiki/Benutzer:FoXFTW/Spielwiese
Images should appear in the "Kopfbild" column, but the "Hersteller" column is replaced instead.

**Comment by kghbln** [comment]
Thanks for reporting! That indeed does not appear to be an expected behaviour.

**Comment by kghbln** [comment]
Reported again as #372 

Still present with:
- MediaWiki | 1.27.4 (317104c)23:34, 7 February 2018
- PHP | 7.0.25-0ubuntu0.16.04.1 (apache2handler)
- MySQL | 5.7.21-0ubuntu0.16.04.1
- Semantic MediaWiki | 2.5.7-alpha (e0c6791) 15:00, 14 February 2018
- Semantic Result Formats | 2.5.5-alpha (aad259d) 15:31, 11 December 2017

Example at [`www.semantic-mediawiki.org`](https://www.semantic-mediawiki.org/wiki/Demo:Datatables_compared_to_broadtable)

**Comment by krabina** [comment]
This must be reopened as it ist sill (or again) present in SRF 3.0
https://www.semantic-mediawiki.org/wiki/Demo:Datatables_compared_to_broadtable

MediaWiki | 1.31.1 (141cb48)22:39, 5 December 2018
PHP | 7.0.32-0ubuntu0.16.04.1 (apache2handler)
MySQL | 5.7.24-0ubuntu0.16.04.1
Lua | 5.1.5

Semantic MediaWiki | 3.0.0 (abdec88) 22:29, 11 October 2018
Semantic Result Formats | 3.0.0 (36ced8d) 09:15, 12 October 2018

**Comment by kghbln** [comment]
@krabina Are you sure. The example page you provided only shows one row of images.

**Comment by kghbln** [comment]
Ok, we have tracked it down. On Linux which I am using Fx is ok and Ch still shows the erroneous behaviour. However in both cases I see the update button on the top right as you can see in the screenshot. This is a second issue.

**Comment by krabina** [comment]
any updates on this? 
I gave datatables another try and encountered the next problem. A property of type boolean displays "t" "f" (true/false) even if you set #ja,nein 
You can see it here: https://sandbox.semantic-mediawiki.org/wiki/Issue/1580

**Comment by krabina** [comment]
https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/482

**Comment by mwjames** [comment]
> any updates on this?

No.

PS: I don't want to sound like a broken record but as long as people don't make a contribution to an issue it is fairly unlikely a core member will come to its rescue. Open source means open to those willing to participate, add new feature, or fix bugs. Open doesn't mean only open to core members! Core members will help and support participants to maintain and retain a quality standard so that the software endures a maintainable state.

**Comment by DaveEvery** [comment]
> No.
> PS: ...but as long as people don't make a contribution to an issue it is fairly unlikely a core member will come to its rescue...

I don't mean this as a jab, but this is a bug reported in 2016 and 5 years later it's not fixed. That seems to scream that nobody on the core team (or elsewhere) cares enough to do maintenance work and keep the code quality up? 

We can argue that there's 2 or 3 other output formats that might work well enough instead. (That's my work-around). But the take away for many is that this doesn't have the critical mass or support value to be relied upon. Unless you have the resources/expertise to fix it yourself. 

So maybe Cargo, WikiDB, Confluence (ick) or some other solution is more reliable?

**Comment by octfx** [comment]
Well I don't think the conclusion that Crago & Co. is more reliable is a correct one.
While MediaWiki is relatively wide used, Wikis with SMW enabled are only a smallish subset, further the subset of SMW installations using this specific type of Result Format + images is even smaller.
This plus finding a user that is versed enough to submit a patch makes the odds of someone submiting a patch in the realms of not "realistic in the next years".

As this is not a critical bug (workarounds exist) members of the core team will use ressources for more critical work.

So in my opinion it is fully understandable that this hasn't seen any momentum in the last few years, _although_ I fully agree with you that a fix for this would be more than welcome.

**Comment by krabina** [comment]
This thread should stay regarding datatables format. I am happy to discuss SMW vs. Cargo or other general issues in separate tickets.
Is datatables working (or even provided) in Cargo?

Regading SMW I always thought that datatables is a very interesting result format, however, for me it never fully worked. Therefore I am using filtered format for most things. Datatables is on of more then 70 formats and I agree that most people have found a way to live without it.

However, I think it is a good idea to leave this open, because who knows someone might have the resources to fix this one day. BTM fixing broken result formats is probably a good entry point for newcomer developers who are very welcome to join in!

**Comment by DaveEvery** [comment]
Thanks. And my whine is just that. It’s just frustrating to go, “hey this is perfect for what I want”… then pound ones head, blame yourself, and only later find out it’s a flaw in the tool. (Cursing/grousing involved). 

The view (output format) is still valuable for non-image data - I just wanted it with that feature, and spent a little too much time trying to debug my code before finding that it was broken, and had been for a long time. 

There’s a learning cliff to get over for doing the first fixes myself. And I want to get much more comfortable with implementation and design patterns before I go spelunking and hacking other people’s code. But I agree that part of the advantage of OpenSource is in the first 1/2 of the name… and being part of the solution is always more constructive than just whining about the problem. The catch 22, is before I invest enough to be able to fix things, I want to make sure it’ll be worth it (solve my problems). 

My poorly worded point was just that 5+ years seemed a bit excessive on pretty primal functionality (for that view). As a noob to SMW, it’s not very turn-key. There’s been a lot of sharp edges (bugs/quirks, config magic, unsupported extensions, etc.), that raise the bar for entry.  But I can see the value, once I get done banging my knees and stubbing toes.  

Thanks, 

Dave

**Comment by Siedlerchr** [comment]
I am currently developing a custom results printer and dug a bit into that code and I think I found the issue, it's an index off by one error. 
https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/bc1ea0ecd7abbbe0e06aced19538f9c20cc4b107/formats/datatables/resources/ext.srf.formats.datatables.js#L171-L172

It must be placed here:
https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/bc1ea0ecd7abbbe0e06aced19538f9c20cc4b107/formats/datatables/resources/ext.srf.formats.datatables.js#L210-L211


Must be moved to the end of the block; otherwise the image info methods will receive the column with index 1, but in fact a zero-based index needed.

**Comment by krabina** [comment]
Looking forward to your commits. Can you create a PR for this, please?

**Comment by Siedlerchr** [comment]
I will try to come up with a PR later.

**Comment by krabina** [comment]
our PR fixes this in my tests
