### ISSUE TITLE
Add integration testing using JSONScript.

### ISSUE THREAD

**Issue by s7eph4n** [SemanticMediaWiki/SemanticResultFormats#220]
Breaking this out of https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2488.

@mwjames, this is too easy. :smiley: Some questions, please:
1. Is there any reason not to directly subclass [SMW\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/JsonTestCaseScriptRunnerTest.php)?
2. Is there documentation available on the RequiredJsonTestCaseMinVersion?

**Comment by mwjames** [comment]
Hi,

> 1. Is there any reason not to directly subclass
> [SMW\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest]

Not really as long as those test case definitions are kept in sync.
One way to ensure that is by defining a
"RequiredJsonTestCaseMinVersion". When we started with this the
structure looked a bit different compared with what it is used now.

Also, as you can see in [1] `prepareTest` is private to control what
settings are permitted to be manipulated to avoid the "everything is
possible" without knowing the consequences and it means that if you
require some repo specific settings then simple subclassing has its
limits.

> 2. Is there documentation available on the RequiredJsonTestCaseMinVersion?

It is to control the script definitions so that each Runner can
specify its own valid required version when defining a JSON structure.
For example, [2] reuses `JsonTestCaseScriptRunner` in its own way and
therefore has a completely different JSON script and versioning.

The check happens at his point [3, 4].

Does this answer your question?

[0] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/2.3.x/tests/phpunit/Integration/ByJsonScript/Fixtures/p-0405%20[%20%23895]%20intext%20annotation%20via%20template%20and%20manual%20redirect.json

[1] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Integration/JSONScript/JsonTestCaseScriptRunnerTest.php#L159-L208

[2] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/Benchmark/BenchmarkJsonScriptRunnerTest.php

[3] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/JsonTestCaseScriptRunner.php#L204-L206

[4] https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/tests/phpunit/JsonTestCaseFileHandler.php#L141-L150

Cheers

**Comment by s7eph4n** [comment]
> > 1. Is there any reason not to directly subclass
> > [SMW\Tests\Integration\JSONScript\JsonTestCaseScriptRunnerTest]
>
> Not really as long as those test case definitions are kept in sync.
> One way to ensure that is by defining a
> "RequiredJsonTestCaseMinVersion". When we started with this the
> structure looked a bit different compared with what it is used now.

Hmm. I intentionally avoided overriding that method in the subclass. If I understand correctly, overriding it would have potentially fixed the stated RequiredJsonTestCaseMinVersion when the functionality of the scriptrunner changed.
I'd rather have the tests fail because of version mismatch than because of some incompatibility.

> Also, as you can see in [1] `prepareTest` is private to control what
> settings are permitted to be manipulated to avoid the "everything is
> possible" without knowing the consequences and it means that if you
> require some repo specific settings then simple subclassing has its
> limits.

That's ok, I think. If and when we need more, we can still extend that list. Could be an idea to extract the list of settings into a protected method, so it can be overridden.

> > 2. Is there documentation available on the RequiredJsonTestCaseMinVersion?
>
> It is to control the script definitions so that each Runner can
> specify its own valid required version when defining a JSON structure.
> For example, [2] reuses `JsonTestCaseScriptRunner` in its own way and
> therefore has a completely different JSON script and versioning.

So from this and from the fact that the version_compare operator is `'ne'` I gather that the RequiredJsonTestCaseMinVersion is in fact a required exact version, right?

It might be an idea to write an actual json schema, which could then be used for validation and to automatically create documentation. So much to do so little time. :)
