### ISSUE TITLE
Value is not declared as a valid unit of measurement for this property.

### ISSUE THREAD

**Issue by camponez** [SemanticMediaWiki/SemanticResultFormats#244]
### Setup

- MW version: 1.28.2
- DB (MySQL etc.): 10.2.6-MariaDB-10.2.6+maria~jessie
- PHP version:7.0.16 (fpm-fcgi)
- SMW version: 2.5.2
- SRF version: -
- Browsers and versions (if applicable): All

### Issue

I have a property type Quantity and i'm getting the error: 

`".50" is not declared as a valid unit of measurement for this property.`

This happens for every decimal number I tried, for example: 10.50, 20.10, 100.00, etc

**Steps to reproduce**

The errors can be seen on this page: https://cruzeiropedia.org/Sandbox

**Comment by mwjames** [comment]
> `".50" is not declared as a valid unit of measurement for this property.`
>
> This happens for every decimal number I tried, for example: 10.50, 20.10,
> 100.00, etc

<swivt:wikiPageContentLanguage
rdf:datatype="http://www.w3.org/2001/XMLSchema#string">pt-br</swivt:wikiPageContentLanguage

> The errors can be seen on this page: https://cruzeiropedia.org/Sandbox

I'm guessing since the content language [0] is `pt-br` and with the
"smw_decseparator" being declared as "," you are required to use `,`
instead of the English `.` for a decimal point.

Unfortunately, the "smw_kiloseparator": "." is missing from the
`pt-br` language and creates an issue as it cannot identify the
correct pair of numeric separators and falls back to English in case
of the kilo separator.

@kghbln Needs to be fixed in SMW-core! Also we should check if the
`smw_decseparator`, `smw_kiloseparator` pair is maintained for all
available languages.

[0] https://www.semantic-mediawiki.org/wiki/Content_language

Cheers

**Comment by mwjames** [comment]
Actually, can we transfer this issue to
https://github.com/SemanticMediaWiki/SemanticMediaWiki.

**Comment by camponez** [comment]
Thanks for the response @mwjames 

>I'm guessing since the content language [0] is `pt-br` and with the "smw_decseparator" being declared as "," you are required to use `,` instead of the English `.` for a decimal point. Unfortunately, the "smw_kiloseparator": "." is missing from the `pt-br` language and creates an issue as it cannot identify the correct pair of numeric separators and falls back to English in case of the kilo separator.

I thought that might be something like that. The problem is that `{{#number_formats ...}}` doesn't like the pt-br format (with comman separator) for decimal numbers. Maybe that's the problem I should fix.

**Comment by kghbln** [comment]
Now at https://github.com/SemanticMediaWiki/SemanticMediaWiki/issues/2510
