### ISSUE TITLE
Filtered format: two issues with Select2 

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticResultFormats#304]
Since the avaialility of the new value filters (Select2) there are two issues:

-  an ampersand in property values used for a filter is displayed as "&amp". This does not happen when checkboxes are used, only in the value filter boxes.
see the "topic" filter here: http://www.bacid.eu/index.php?title=Governance_Tool_Database&direction=next&oldid=3317

- the select 2 fiield is broken if on the same page a page form is used.
http://www.bacid.eu/index.php?title=Governance_Tool_Database&oldid=3317

**Comment by s7eph4n** [comment]
1. Should be fixed in master and on the 2.5.x branch now.
2. I have no idea how to fix this in SRF. PageForms uses a 5 year old version of the Select2 lib and as far as I can see there is no way of making the two versions co-exist. One way of fixing this would be if PageForms was updated. Or if it only loaded the lib when really necessary.

**Comment by krabina** [comment]
@yaronkoren - are there plans to update Select2 library in PageForms?

**Comment by s7eph4n** [comment]
Won't fix the compatibility issues with PageForms.  Downgrading to accommodate PF does not make sense, IMO.
