### ISSUE TITLE
Hiding internal event hashes

### ISSUE THREAD

**Issue by fraxinas** [SemanticMediaWiki/SemanticResultFormats#566]
### Setup

- MW version: `1.31.1`
- DB (MySQL etc.): `10.1.41-MariaDB-0+deb9u1`
- PHP version: `7.0.33-14+0~20191218.25+debian9~1.gbpae1889 (fpm-fcgi)`
- SMW version: `3.1.0`
- SRF version: `3.1.0`

### Issue

@kghbln referred me from the semediawiki-user list to here.

We've been using semantic events for auto-generating calendars for our maker space. 
The way events are queried are with:
```
{{#ask: [[Has event start::>={{CURRENTYEAR}}-{{CURRENTMONTH}}-{{CURRENTDAY}}]] 
(and a few properties...)
}}
```
we also provide icalendar files.
However, all the events expose their internal reference uids in a lengthy hash that is 
appended after the article name, e.g. https://wiki.schaffenburg.org/Kurs:2D-CAD#_6083d8864bb5c1ee52083c8272a97078

This is especially annoying in the ical, because it doesn't just show up in the status bar as the 
URI field but is the actual visible event name.

Is it possible to hide these hashes from the results so that the links look more like this:
https://wiki.schaffenburg.org/Kurs:2D-CAD ?

Our calendar is public on this address: https://wiki.schaffenburg.org/Termine

What maybe interesting: If the query is done through the category rather than the `event start` property, then there's no hash in the url
```
{{#ask:  [[Kategorie:Kurs]]
 [[Datum::<{{CURRENTYEAR}}-{{CURRENTMONTH}}-{{CURRENTDAY}}]]
}}
```

**Comment by mwjames** [comment]
> However, all the events expose their internal reference uids in a lengthy hash that is
appended after the article name, e.g. https://wiki.schaffenburg.org/Kurs:2D-CAD#_6083d8864bb5c1ee52083c8272a97078

First of all, the mentioned output works as expected as it allows to distinguish each event as an individual entity.

When used as part of a recurring event, events are created as individual entities (also know as subobject) to identify each event. In your case, `_6083d8864bb5c1ee52083c8272a97078` identifies [0] the event entity that represent a specific instance that declares a start and end date together with other properties that are only relevant for that particular instance. If you remove that identifier then you remove the semantics which defines an individual representation. 

For example, if you declare a date and start on page `Foo` then the individual event instance is referenced to the entity `Foo` (in wiki terms to the page `Foo`). Now, If you wanted to create different events on the same page you would need to distinguish them otherwise events are indistinguishable from each other and is the reason why `#set_recurring_event` [1] creates subobjects on the page that embeds the parser function.

> Is it possible to hide these hashes from the results so that the links look more like this:
https://wiki.schaffenburg.org/Kurs:2D-CAD ?

Of course, you can remove that representation using your own result printer but I'm unlikely to support any modification in SRF to iCal itself that would remove such distinction for the reasons given above.

> What maybe interesting: If the query is done through the category rather than the event start property, then there's no hash in the url

Well, yes because you only select entities that are "connected" to that category. Subobjects can be connected to categories but have to be explicitly defined [2].

[0] https://www.semantic-mediawiki.org/wiki/Help:Adding_subobjects#Anonymous_identifier
[1] https://www.semantic-mediawiki.org/wiki/Help:Recurring_events
[2] https://www.semantic-mediawiki.org/wiki/Help:Adding_subobjects#Using_categories

**Comment by fraxinas** [comment]
So an .ical File is _supposed_ to have Recurring Events _named_ like this?
![image](https://user-images.githubusercontent.com/1109826/72669614-60810500-3a34-11ea-89d6-c72d1b9a6544.png)

**Comment by mwjames** [comment]
> This is how they are displayed in a calendar application.

Again, each of these events represent individual entities. Now, if you would create single pages for these events then you would be able to follow the simple annotation practice of assigning start/end to each page hereby render them as individuals (as seen for 2D-CAD), yet as soon as more than one entity representation is to be created from a page without taken the page as individual into account you have distinguish them and that is done by isolating their entity space which is addressed via a specific hash ID (as visible in the above screen dump).

> I'd understand it if it had the hash in the URI but with proper titles but this looks very cryptic to any user.

I understand that, and as I said you can write your own result printer to make custom modifications specific to your needs but I won't support modifications to the default iCal printer that would make those entities appear as being a simple "page" hereby being indistinguishable from other entities with the same parent. This would foster the wrong concept about the data model used to represent the data.

PS: I do understand your request but I cannot accommodate that by making the iCal printer to produce "wrong" data because for example, "Kurs:2D-CAD#_6083d8864bb5c1ee52083c8272a97078" is something entirely different than "Kurs:2D-CAD".

**Comment by mwjames** [comment]
@kghbln I can't shake the feeling that people still have problems to understand what an entity space is and how sub-entities are treated as individuals. It could be that the documentation isn't clear about the fact that those sub-entities (aka. subobjects) are isolated representation (aka. containers) of data and while sharing a common entity space (that of the page) define their own to be addressable as individuals.

![image](https://user-images.githubusercontent.com/1245473/72670300-f0727f00-3a33-11ea-86c9-73614ba2a5b9.png)

**Comment by kghbln** [comment]
The reason why I suggested that it my be feasible to add this as a feature request is that the subobject tied to the respective page, i.e. if you browse to "Foo#_SubobjectHash" you still end up on page "Foo" and this is basically all one needs as a consumer when using the ical file. 

I think that the difference between object and subobject was understood here.

**Comment by mwjames** [comment]
> The reason why I suggested that it may be feasible to add this as a feature request is that the subobject is tied to the respective page, i.e. if you browse to "Foo#_SubobjectHash"

Browsing and data representation are different aspects here where `Foo#_SubobjectHash` with `#` being the HTML indicator for a fragment will always refer to the initial literal that comes before the `#`, yet for SMW it refers to an individual entity.

**Comment by mwjames** [comment]
> I can't shake the feeling that people still have problems to understand what an entity space is and how sub-entities are treated as individuals.
> I think that the difference between object and subobject was understood here.

[0] hopefully clarifies the topic and should be used as reference for future questions in regards as to why those hashes appear and what they imply.

[0] https://www.semantic-mediawiki.org/wiki/Entity

**Comment by krabina** [comment]
@fraxinas can we close this or is this still a problem?

**Comment by fraxinas** [comment]
> @fraxinas can we close this or is this still a problem?

The problem persists for us.

**Comment by krabina** [comment]
But you have solved it on https://wiki.schaffenburg.org/Termine 
I cannot see any problems there.

**Comment by krabina** [comment]
Since you have the property has title, should it not be enough to add |mainlabel=- to avoid the output of the subobject page names?

**Comment by fraxinas** [comment]
Hi Krabina, thanks for the suggestion!

You mean like this?
```
{{#ask: [[Has event start::>={{CURRENTYEAR}}-{{CURRENTMONTH}}-{{CURRENTDAY}}]]
 |?Has title=summary
 |?Has event start=start
 |?Has event end=end
 |?Has event description=description
 |?Has event url=url
 |?location=location
 |title=Schaffenburg (Komplett)
 |searchlabel=Schaffenburg (Komplett).ics
 |limit=1000
 |format=icalendar
 |mainlabel=-
 |description=Veranstaltungskalender mit allen Termine des Makerspace Schaffenburg e.V.
}}
```

I changed it in this way, but the labels remain.

**Comment by krabina** [comment]
That is what I meant, but it seems to be not what is needed. Look at the sandbox example:
https://sandbox.semantic-mediawiki.net/wiki/Recurring_events#iCalendar
Since it is working there and sandbox is also using subobjects, it could have to do with your versions being outdated or some kind of difference in data structure. 

I am closing this here, since the working sandbox example shows that an iCalendar output without the markers can be achieved.

Feel free to comment further on this issue once you have found a solution or upgraded your installation.
