### ISSUE TITLE
[gallery] Gallery is not neccesarily rendered immediately and needs a purge page to do so

### ISSUE THREAD

**Issue by the1gofer** [SemanticMediaWiki/SemanticResultFormats#620]
### Setup

- MW version: 1.35
- DB (MySQL etc.): mysql
- PHP version: 7.3
- SMW version: 3.2
- SRF version: 3.2

### Issue

example:  https://www.crewsgenealogy.com/wiki/Florida_militia_muster_rolls,_Seminole_Indian_Wars.  Screen shot if it gets fixed: https://www.dropbox.com/s/7rcsg1ji35ahvaf/Screen%20Shot%202020-10-25%20at%204.59.57%20PM.png?dl=0

**Steps to reproduce**
I'm not exactly sure what causes it, but I can fix it by removing the trailing space at the end of the template on that page.   Mediawiki seems to insist on adding the space back from time to time, so I keep running into the problem.  It's not just onlthis page. 

**Expected result:**
Gallery format should be used, bot a bulleted list of images

**Observed result:**
see screenshot

**Comment by JeroenDeDauw** [comment]
You can attach images here

**Comment by the1gofer** [comment]
<img width="784" alt="Screen Shot 2020-10-25 at 4 59 57 PM" src="https://user-images.githubusercontent.com/2140724/97123395-eed39700-16e8-11eb-9961-3dd53b02665c.png">

**Comment by markmuzenhardt** [comment]
We at fuerthwiki.de have the same Problem. MediaWiki 1.35, PHP 7.4, MySQL 5.7, SMW 3.2.1.
If an article is saved, maybe the semantic gallery is rendered as bullet list instead of a gallery. Sometimes, if you save a second time, the galery gets rendered properly, sometimes not.

**Comment by Sophivorus** [comment]
Same issue. Also, it seems that MORE OFTEN THAN not galleries render incorrectly, and a gallery that renders correctly will render incorrectly after a simple refresh or two, and from then on will render always incorrectly, so this bug effectively breaks the gallery result format. See for example https://www.appropedia.org/Template:Gallery/sandbox

**Comment by ChieftainAlex** [comment]
We've got the same [issue on our wiki](https://wiki.guildwars2.com/wiki/Guild_Wars_2_Wiki:Reporting_wiki_bugs#SMW_galleries_appearing_as_a_column), which uses SRF 3.2.0 //  SMW 3.2.3 // MW 1.35.2

I agree it seems to be a CSS issue. Using debug=true I was able to identify that the missing CSS module is **[modules=mediawiki.page.gallery.styles](https://wiki.guildwars2.com/load.php?debug=true&lang=en&modules=mediawiki.page.gallery.styles&only=styles)**

Bizarrely the exact same CSS module loads perfectly every time when **previewing** a page edit, but submitting it usually results in the column appearance due to the module not being requested. Sometimes a purge/refresh fixes it for a brief moment.

As a workaround I intend to paste the above module's css into our site's common.css.

Example page:
https://wiki.guildwars2.com/index.php?title=Gallery_of_Roller_Beetle_skins

**Comment by gesinn-it-gea** [comment]
We had a look into this issue and it seems to be related to caching. @ChieftainAlex is correct with the CSS module missing (in case the page is loaded from cache) and with the page looks good in preview (which bypasses cache).

@the1gofer @Sophivorus @markmuzenhardt can you try to temp. disable caching with:

```
$wgMainCacheType = CACHE_NONE;
$wgParserCacheType = CACHE_NONE;
$wgMessageCacheType = CACHE_NONE; 
```
Make sure, PHP's OPCache is disable so that the above changes have effect.

With disable cache, gallery should always be rendered correct.

**Comment by Sophivorus** [comment]
Hi! I just verified that setting `$wgMainCacheType = CACHE_NONE;` sufficed for my case, so the diagnosis seems correct.

**Comment by the1gofer** [comment]
confirmed, that seems to work.

Jason Crews
