### ISSUE TITLE
Datatables with Foreground Skin: Rendering of the search button and pagination is buggy

### ISSUE THREAD

**Issue by Scale51** [SemanticMediaWiki/SemanticResultFormats#82]
Hello,

I got some problems using the extension in my mediawiki environment. I am using Foreground as skin and I am trying to display some data with the datatables from the extension. As you can see in the screenshot the search button on the top right and the pagination on the buttom are not displayed correctly. Do you have any idea how to solve this problem?

![example](https://cloud.githubusercontent.com/assets/10723299/5916826/da1b914a-a615-11e4-823b-4731166d66be.PNG)

Versions:
MediaWiki	1.24.1
Semantic MediaWiki	2.1
Semantic Result Formats	2.0
Foreground	1.2-alpha (7d098d2)

**Comment by mwjames** [comment]
The default theme is to use `bootstrap` [0] which I believe conflicts with whatever Foreground provides as container/css classes. I don't have time to look at this issue because the standard vector-skin is working as expected [1].

[0] https://github.com/SemanticMediaWiki/SemanticResultFormats/blob/master/formats/datatables/DataTables.php#L81

[1] https://www.semantic-mediawiki.org/wiki/Video_collection

A PR that provides a fix or enhancement to resolve this issue is more than welcome but since it is specific to the Foreground Skin, I'm inclined to close this issue.
